---
title: "Parenting Project Attitudes Questionnaire Experiment 1"
author: "Emily & Mike"
date: "`r Sys.Date()`"
---

Preliminaries.

```{r}
rm(list=ls())
library(langcog)
library(dplyr)
library(ggplot2)
library(rjson)
library(stringr)
theme_set(theme_bw())
```

Read in files and consolidate to the same directory. 

```{r}
files <- dir("../production-results/e1-pilot/")
d.raw <- data.frame()

for (f in files) {
  jf <- paste("../production-results/e1-pilot/",f,sep="")
  jd <- fromJSON(paste(readLines(jf), collapse=""))
  id <- data.frame(workerid = jd$WorkerId, 
                   sent = jd$answers$data$sent,
                   rating = as.numeric(jd$answers$data$rating),
                   children = jd$answers$data$children,
                   language = jd$answer$data$language)
  d.raw <- bind_rows(d.raw, id)
}
```

Note there is a repeat item here, "abstract concepts from good behavior."

Map on question short forms so that we can use these instead. 

```{r}
labels <- read.csv("sent_forms.csv")
labels$sent <- as.character(labels$sent)
d.raw$sent <- as.character(d.raw$sent)
d.raw$sent <- str_replace_all(d.raw$sent, "'", "")
d.raw$sent <- str_replace_all(d.raw$sent, "’", "")
d.raw$sent <- str_replace_all(d.raw$sent, "“", "")
d.raw$sent <- str_replace_all(d.raw$sent, "”", "")
d.raw$sent <- str_replace_all(d.raw$sent, "‘", "")

d <- left_join(d.raw, labels)
```

Now look at mean ratings across sentences.

```{r}
ms <- d %>%
  group_by(short_sent, category) %>%
  summarise(rating = mean(rating)) 

qplot(short_sent, rating, col = category, data = ms) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)) 
```

And by whether they have kids. 

```{r}
ms <- d %>%
  mutate(kids = children == "yes") %>%
  group_by(short_sent, category, kids) %>%
  summarise(rating = mean(rating)) 

qplot(short_sent, rating, col = category, data = ms) +
  facet_grid(kids ~ .) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)) 
```

